#!/bin/bash

# Define the list of files

files=(
"19_testing7_ncc_health_checks_run_all_gg_command.yml"
"20_testing7_ncc_health_checks_run_all_gg_python.yml"
"21_testing7_ncc_health_checks_run_all_gg_shell.yml"
"22_testing7_ncc_health_checks_run_all_allcvms_gg_command.yml"
)

#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))

# Loop through each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"
        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile

        echo "" >> $outfile
        echo "" >> $outfile
        echo aph "$file" >> $outfile
        echo "" >> $outfile
        aph "$file" >> $outfile
        echo Processing "$file" finished
        echo
#        sleep 1
    else
        echo "Error: $file not found."
    fi
done


