---
- name: 1. Run diagnostic commands on all CVMs
#  hosts: corecvm
  hosts: allcvms
  gather_facts: false
  serial: 1

  vars:
    cmd_list:
#      - name: hostips
#        argv: ["hostips"]

#      - name: hostssh ovn-appctl connection-status
#        argv: ["hostssh", "ovn-appctl", "connection-status"]

      - name: hostssh nvidia-smi
        argv: ["hostssh", "nvidia-smi"]

#      - name: hostssh systemctl status dbus
#        argv: ["hostssh", "systemctl", "status","dbus"]

#      - name: hostssh systemctl status nvidia-vgpu-mgr
#        argv: ["hostssh", "systemctl", "status","nvidia-vgpu-mgr"]

#      - name: hostssh systemctl list-units --type=service --no-pager
#        argv: ["hostssh", "systemctl", "list-units", "--type=service", "--no-pager"]

  tasks:
    - name: 2. Execute commands
      include_tasks: subr.02.testing10_hosting_commands.yml
      loop: "{{ cmd_list }}"
      loop_control:
        loop_var: cmd

    - name: 3. Display input_result.stdout_lines
      ansible.builtin.debug:
        var: input_result.stdout_lines

    - name: 3. Display input_result.stdout
      ansible.builtin.debug:
        var: input_result.stdout

    - name: 3. Display input_result.stderr
      ansible.builtin.debug:
        var: input_result.stderr

