#!/bin/bash

# Define the list of files
#files=("file1.txt" "file2.txt" "file3.txt")

files=(
"02.testing10_hostssh_commands.yml"
"03.testing10_hostssh_dbus_hostssh_commands.yml"
"03.testing10_hostssh_dbus_hostssh_commands.yml.org"
"04.testing10_hostssh_allcvms_dbus_hostssh_commands.yml"
"05.testing10_hostssh_nvidia_vgpu_mgr_hostssh_commands.yml"
"06.testing10_hostssh_allcvms_nvidia_vgpu_mgr_hostssh_commands.yml"
"07.testing10_hostssh_ovn_hostssh_commands.yml"
"40.testing10_hostssh_ovn_lab_logic.yml"
"42.testing10_hostssh_systemctl_status_nvidia_vgpu_mgr_logic.yml"
"44.testing10_hostssh_systemctl_status_dbus_logic.yml"
"46.testing10_hostssh_nvidia_smi_logic.yml"
"subr.02.testing10_hosting_commands.yml"
"subr.03.testing10_hostssh_dbus_hostssh_commands.yml"
"subr.05.testing10_hostssh_nvidia_vgpu_mgr_hostssh_commands.yml"
"subr.07.testing10_hostssh_ovn_hostssh_commands.yml"
"subr.40.testing10_hostssh_ovn_lab_logic.yml"
"subr.42.testing10_hostssh_systemctl_status_nvidia_vgpu_mgr_logic.yml"
"subr.44.testing10_hostssh_systemctl_status_dbus_logic.yml"
"subr.46.testing10_hostssh_nvidia_smi.yml"
)


#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))

# Loop through each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"
        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile


        if [[ ${file:0:4} != 'subr' ]]; then

           echo "" >> $outfile
           echo "" >> $outfile
           echo aph "$file" >> $outfile
           echo "" >> $outfile
           aph "$file" >> $outfile
           echo Processing "$file" finished
           echo
#         sleep 1
        fi
    else
        echo "Error: $file not found."
    fi
done


