---
- name: Pseudo hostssh - Check nvidia-vgpu-mgr
  hosts: corecvm
  gather_facts: false

  vars:
    read_from_file: false 
    logd_enabled: false 
    role_enabled: false 
    log_filesystem_enabled: false 
    log_github_enabled: false 

  tasks:
    - name: -1. Declare flags
      set_fact:
        remote_user_name: nutanix

    - name: Process AHV hosts configuration and tracking
      when: not (read_from_file | bool)
      block:
        - name: 1. Declare variables
          set_fact:
            answer: "Healthy"
            remark: "No failures or errors detected."
    
        - name: 2. Get AHV host IP addresses
          ansible.builtin.command:
            argv:
              - /bin/bash
              - -c
              - |
                source /etc/profile
                hostips
          register: hostips_output
          changed_when: false
    
        - name: 3. Parse IP addresses into a clean list
          ansible.builtin.set_fact:
            ahv_hosts: "{{ hostips_output.stdout | regex_findall('[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+') }}"
    
        - name: 4. Initialize the empty input_result structures
          ansible.builtin.set_fact:
            input_result_stdout_list: []
            input_result_lines_list: []
    
        - name: 5. Calling the subroutine
          ansible.builtin.include_tasks: subr.42.testing11_hostssh_systemctl_status_nvidia_vgpu_mgr_logic.yml
          loop: "{{ ahv_hosts }}"
          loop_control:
            loop_var: current_host
          when: ahv_hosts | length > 0
    
        - name: 6. Construct final input_result dictionary
          ansible.builtin.set_fact:
            input_result:
              stdout: "{{ input_result_stdout_list | join('\n') }}"
              stdout_lines: "{{ input_result_lines_list }}"

        - name: 7. Debug and display aggregate input_result outputs
          ansible.builtin.debug:
            var: input_result.stdout_lines

    - name: 8. Mimic 'cat' register output using lookup
      set_fact:
        input_result:
          stdout: "{{ lookup('file', 'data.42.testing11_hostssh_systemctl_status_nvidia_vgpu_mgr_logic.txt') }}"
          stdout_lines: "{{ lookup('file', 'data.42.testing11_hostssh_systemctl_status_nvidia_vgpu_mgr_logic.txt').splitlines() }}"
          rc: 0
          failed: false
          changed: false
      when: read_from_file | bool

    - name: 9. Display input_result.stdout_lines
      ansible.builtin.debug:
        msg: "{{ input_result.stdout }}" 

    - set_fact:
        svc_list: >-
          {{
            input_result.stdout | regex_findall(
            '={1,20}\s*([0-9.]+)\s*={1,20}.*?\n.*?(nvidia-vgpu-mgr\.service).*?\n.*?\n.*?Active:\s+(\w+)',
            multiline=True
            )
          }}
    
    - name: 10. Determine svc_list
      debug:
        var: svc_list

    - set_fact:
        answer: "None"
      when: svc_list | length == 0
    
    - set_fact:
        inactive_list: "{{ svc_list | rejectattr('2', 'equalto', 'active') | list }}"
      when: svc_list | length > 0
    
    - set_fact:
        answer: >-
          {{ 'All active' if inactive_list | length == 0 else 'Not all active' }}
        remark: >-
          {{ inactive_list if inactive_list | length > 0 else '' }}
      when: svc_list | length > 0

    - name: 11. Display answer and remark
      debug:
        msg: "{{ answer }} {{ remark }} "

    - name: 99. Include persistency
      ansible.builtin.include_tasks: incl.logging.yml
