---
- name: Export CSV Data and Push to GitHub 
  hosts: localhost
  gather_facts: false
  vars:
    # Fallback to variable if env is not set
    gh_token: "{{ lookup('env', 'GITHUB_TOKEN') | default(github_token, true) }}"
    repo_url: "github.com/ilovefreebee3-svg/healthmonitoring.git"
    clone_dir: "/tmp/healthmonitoring"
    csv_filename: "health_report.csv"

  tasks:
    - name: Ensure GitHub token is provided
      fail:
        msg: "The variable 'gh_token' or 'GITHUB_TOKEN' env variable is missing!"
      when: gh_token | length == 0

    - name: display variabe
      ansible.builtin.debug:
        var: gh_token

#    - name: Generate the CSV file data
#      copy:
#        content: |
#          Timestamp,Host,Status,CPU_Usage,Memory_Usage
#          {{ ansible_date_time.iso8601 | default(now().iso8601) }},server1,Healthy,12%,45%
#          {{ ansible_date_time.iso8601 | default(now().iso8601) }},server2,Warning,88%,91%
#        dest: "/tmp/{{ csv_filename }}"

    - name: Set message of the day
      ansible.builtin.copy:
        content: "Welcome to {{ inventory_hostname }}. Managed by Ansible. Last updated: 1611\n"
        dest: "/tmp/{{ csv_filename }}"

    - name: Clean up any existing temporary clone directory
      file:
        path: "{{ clone_dir }}"
        state: absent

    - name: Clone the healthmonitoring repository using token authentication
      git:
        repo: "https://{{ gh_token }}@{{ repo_url }}"
        dest: "{{ clone_dir }}"
        version: main
        force: true

    - name: Copy generated CSV file to the repository directory
      copy:
        src: "/tmp/{{ csv_filename }}"
        dest: "{{ clone_dir }}/{{ csv_filename }}"

    - name: Configure Git user identity locally for this execution
      shell: |
        git config user.name "ilovefreebee3-svg"
        git config user.email "ilovefreebee3@gmail.com"
      args:
        chdir: "{{ clone_dir }}"

    - name: Check if there are changes to commit
      shell: git status --porcelain
      args:
        chdir: "{{ clone_dir }}"
      register: git_status
      changed_when: false

    - name: Commit and push the CSV file if changes exist
      shell: |
        git add .
        git commit -m "Automated CSV export update"
        git push https://x-oauth-basic:{{ gh_token }}@:github.com HEAD:main
      args:
        chdir: "{{ clone_dir }}"
      when: git_status.stdout | length > 0

#    - name: Commit and push the CSV file if changes exist
#      shell: |
#        git add {{ csv_filename }}
#        git commit -m "Automated update: Uploaded {{ csv_filename }} via AWX"
#        git push origin main
#      args:
#        chdir: "{{ clone_dir }}"
#      when: git_status.stdout | length > 0

    - name: Wipe temporary clone directory to keep AWX environment clean
      file:
        path: "{{ clone_dir }}"
        state: absent
 
