[home]
sk1

[home1]
server_1
server_2
server_3
server_4
server_5
server_6
server_7
server_8
server_9
server_10
server_11
server_12
server_13
server_14
server_15
server_16
server_17
server_18
server_19

[production]
server_A
server_B
server_C

[lab]
server_1
server_2
server_3
server_4
server_5
server_6
server_7
server_8
server_9
server_10
server_11
server_12
server_13
server_14
server_15
server_16
server_17
server_18
server_19

[home:vars]
ansible_user=nutanix

[lab:vars]
ansible_user=nutanix
