---
- name: 0. Declare variables
  set_fact:
    awx_host_ip: "130.8.20.99"
    host_destination_path: "/home/user1/daily_report.csv"

#- name: Append result to CSV (local)
#  delegate_to: localhost
#  lineinfile:
#    path: "./output_{{ lookup('pipe','date +%Y%m%d') }}.csv"
#    create: yes
#    line: "{{ inventory_hostname }}, {{ answer }}, {{ remark }}"
#  when: logd_enabled | bool

- name: Append result to CSV (role)
  delegate_to: localhost
  lineinfile:
    path: "./output_{{ lookup('pipe','date +%Y%m%d') }}.csv"
    create: yes
    line: "{{ inventory_hostname }}, {{ role }}, {{ vpc }}, {{ description }}, {{ idx }}, {{ answer }}, {{ remark }} "

- name: Export files to AWX host
  delegate_to: "{{ awx_host_ip }}"
  when: log_filesystem_enabled | bool
  block:
    - name: 2a. Force create destination directory structure in home folder
      ansible.builtin.command: "mkdir -p /home/user1/awx_exports"

    - name: 2b. Copy file from container to the AWX host filesystem
      ansible.builtin.copy:
        src: "./output_{{ lookup('pipe','date +%Y%m%d') }}.csv"
        dest: "/home/user1/awx_exports/."
        mode: '0644'

- name: 3. Export file to github
  ansible.builtin.include_tasks: subr.gitexport.yml
  vars:
    csv_filename: "health_report1.csv"
  when: log_github_enabled | bool 

