#!/bin/bash

# Define the list of files
#files=("file1.txt" "file2.txt" "file3.txt")

files=(
"02_testing8_others_cs_grep_v_up_command_gg.yml"
"10_testing8_allssh_docker_ps_a_exited_up_no_sudo_gg.yml"
"11_testing8_allssh_ll_calm_backup_gg.yml"
"12_testing8_allssh_ls_larth_iam_backup_gg.yml"
"13_testing8_allssh_sudo_kubectl_get_pods_a_gg.yml"
"14_testing8_allssh_df_kh_grep_elastic_gg.yml"
"15_testing8_allssh_curl_get_catalog_k_P1ASEC018.yml"
"16_testing8_allssh_curl_get_catalog_k_P1SMG025.yml"
"17_testing8_allssh_df_h_sdb3_gg.yml"
"31_testing8_mspctl_debug_run_command_with_logic_site_data.yml"
"32_testing8_mspctl_debug_run_test_exclude_subset_site_data.yml"
"33_testing8_mspctl_cluster_health_command_msp.yml"
"34_testing8_mspctl_cluster_health_command_s3.yml"
"35_testing8_mspctl_cluster_health_command_prism-central.yml"
"51_testing8_ncc_health_checks_run_all_gg_command.yml"
"62_testing8_others_ssh_calm_policy_gg.yml"
"subr.run_allssh_no_unreachable.yml"
"subr.run_allssh.yml"
)

#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
#post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))
todaydate=$(( $(date +%d) ))
post=${todaydate}.$(( 10#$(date +%H) * 60 + 10#$(date +%M) ))

# Loop through each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"
        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile


        if [[ ${file:0:4} != 'subr' ]]; then

           echo "" >> $outfile
           echo "" >> $outfile
           echo aphe "$file" >> $outfile
           echo "" >> $outfile
           aphe "$file" >> $outfile
           echo Processing "$file" finished
           echo
#         sleep 1
        fi
    else
        echo "Error: $file not found."
    fi
done


