---
- name: 11. Display host and command
  ansible.builtin.debug:
    msg:
      - "Host    : {{ inventory_hostname }}"
      - "Command : {{ cmd.name }}"

- name: 12. Run command
  ansible.builtin.command:
    argv:
      - /bin/bash
      - -c
      - |
        source /etc/profile
        {{ cmd.name }}
  register: input_filter
  changed_when: false
  failed_when: false

- name: 13. Declare variables
  set_fact:
    answer: "Healthy"
    remark: "No failures or errors detected."

#- name: 14. Mimic 'cat' register output using lookup. This block should be deleted.
#  set_fact:
#    input_filter:
#      stdout: "{{ lookup('file', 'data.40.testing11_hostssh_ovn_lab_logic.txt') }}"
#      stdout_lines: "{{ lookup('file', 'data.40.testing11_hostssh_ovn_lab_logic.txt').splitlines() }}"
#      rc: 0
#      failed: false
#      changed: false
#  when: read_from_file

- name: 15. Return code
  ansible.builtin.debug:
    var: input_filter.rc

- name: 16. Debug the captured output
  ansible.builtin.debug:
    var: input_filter.stdout_lines

- name: 17. Display the captured output
  ansible.builtin.debug:
    var: input_filter.stdout

- name: 18. Display {{ cmd.argv }} command output
  debug:
    msg: |
      ==================================================
      Host    : {{ inventory_hostname }}
      Command : {{ cmd.name }}
      RC      : {{ input_filter.rc }}

      STDOUT:
      {{ input_filter.stdout_lines | default('') }}

      STDERR:
      {{ input_filter.stderr | default('') }}
      ==================================================

#- name: 19. Log output on control node
#  ansible.builtin.blockinfile:
#    path: ./tmp/00_run_all_hostssh_commands.log
#    create: true
#    marker: ""
#    block: |
#      ==================================================
#      Host    : {{ inventory_hostname }}
#      Command : {{ cmd.name }}
#      RC      : {{ input_filter.rc }}
#
#      STDOUT:
#      {{ input_filter.stdout_lines | default('') }}
#
#      STDERR:
#      {{ input_filter.stderr | default('') }}
#      ==================================================
#  delegate_to: localhost
#  ansible_connection: local
