#!/bin/bash

# Define the list of files
#files=("file1.txt" "file2.txt" "file3.txt")


files=(
"03C_testing8_mspctl_cluster_health_command_msp.yml"
"03D_testing8_mspctl_cluster_health_command_s3.yml"
"03E_testing8_mspctl_cluster_health_command_pc.yml"
"10_testing8_mspctl_cluster_list_logic.yml"
"11_testing8_mspctl_cluster_list.yml"
"14_testing8_allcvms_mspctl_debug_run_command_with_logic_site_data.yml"
"18_testing8_allcvms_mspctl_debug_run_command_with_logic_site_sUCCESS_data.yml"
"31_testing8_mspctl_debug_run_test_exclude_subset_command.yml"
"32.testing9_mspctl_debug_run_command_site.yml"
"33.testing9_mspctl_debug_run_exclude_command_site.yml"
"34_testing8_allcvms_mspctl_debug_run_test_exclude_subset_site_data.yml"
)

#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))

# Loop through each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"
        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile

        if [[ ${file:0:4} != 'subr' ]]; then
           echo "" >> $outfile
           echo "" >> $outfile
           echo aph "$file" >> $outfile
           echo "" >> $outfile
           aph "$file" >> $outfile
           echo Processing "$file" finished
           echo
#         sleep 1
        fi
    else
        echo "Error: $file not found."
    fi
done


