---
- name: Initialize report
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Generate CSV filename once
      ansible.builtin.set_fact:
        csv_filename: "output.{{ now().strftime('%Y%m%d.%H%M') }}.csv"

    - name: Reset CSV report
      ansible.builtin.copy:
        content: ""
        dest: "{{ csv_filename }}"
        mode: '0644'

    - name: Display CSV filename
      ansible.builtin.debug:
        msg: "CSV filename = {{ csv_filename }}"


- name: Generate report
  hosts: lab3
  gather_facts: false
  serial: 1

  tasks:

    - name: Display csv_filename
      ansible.builtin.debug:
        msg: "{{ hostvars['localhost']['csv_filename'] }}"

    - name: Run report command
      ansible.builtin.command:
        cmd: "hostname -I"
      register: report_result

    - name: Display report_result
      ansible.builtin.debug:
        msg: "{{ report_result }}"

    - name: 3. Display csv_filename
      ansible.builtin.debug:
        msg: "{{ hostvars['localhost']['csv_filename'] }}"

    - name: Append result to CSV
      ansible.builtin.lineinfile:
#        path: "/runner/project/{{ hostvars['localhost']['csv_filename'] }}"
        path: "{{ hostvars['localhost']['csv_filename'] }}"
        line: "{{ inventory_hostname }},{{ report_result.stdout }}"
        create: true
      delegate_to: localhost
