---
- name: 1. Run diagnostic commands on all CVMs
  hosts: pecvm
#  hosts: corecvm
#  hosts: allcvms
  gather_facts: false
  serial: 1

  vars:
    cmd_list:
      - name: svmips
        argv: ["svmips"]

      - name: __allssh df -h /dev/sdb3
        argv: ["allssh", "df", "-h","/dev/sdb3"]

      - name: /home/nutanix/cluster/bin/allssh 'ls -l /home/nutanix/tmp/calm-bkup'
        argv: ["allssh", "ls", "-ls","/home/nutanix/tmp/calm-bkup"]

      - name: /home/nutanix/cluster/bin/allssh 'ls -larth /usr/local/nutanix/iam-backup'
        argv': ["allssh", "ls", "-larth", "/usr/local/nutanix/tmp/iam-backup"]

      - name: /home/nutanix/cluster/bin/allssh docker ps -a
        argv: ["allssh", "docker", "ps", "-a"]

      - name: /home/nutanix/cluster/bin/allssh kubectl get pods -A
        argv: ["allssh", "kubectl", "get", "pods", "-A"]

      - name: /home/nutanix/cluster/bin/allssh docker ps -a
        argv: ["allssh", "docker", "ps", "-a"]

      - name: /home/nutanix/cluster/bin/allssh sudo kubectl get pods -A
        argv: ["allssh", "sudo", "kubectl", "get", "pods", "-A"]

      - name: /home/nutanix/cluster/bin/allssh sudo docker ps -a
        argv: ["allssh", "sudo", "docker", "ps", "-a"]

      - name: /home/nutanix/cluster/bin/allssh curl -X GET https://P1ASEC018.dcloudsvc.gov.sg:5000/v2/_catalog -k
        argv: ["allssh", "curl", "-X", "GET", "https://P1ASEC018.dcloudsvc.gov.sg:5000/v2/_catalog", "-k"]

  tasks:
    - name: 2. Execute commands
      include_tasks: subr.18.testing10_allssh_commands.yml
      loop: "{{ cmd_list }}"
      loop_control:
        loop_var: cmd

    - name: 3. Debug the captured output
      ansible.builtin.debug:
        var: input_result

