#!/bin/bash

# Define the list of files
#files=("file1.txt" "file2.txt" "file3.txt")

files=(
"18.testing10_allssh_commands.yml"
"subr.18.testing10_allssh_commands.yml"
)

#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))

#output=output.$post
#echo $output
# Loop through each file

for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"

        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile


        if [[ ${file:0:4} != 'subr' ]]; then
           echo "" >> $outfile
           echo "" >> $outfile
           echo aph "$file" >> $outfile
           echo "" >> $outfile
           aph "$file" >> $outfile
           echo Processing "$file" finished
           echo
#           sleep 1
        fi
    else
        echo "Error: $file not found."
    fi
done


