---
- name: Run local color script
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: 1. Execute the bash script and capture output
      ansible.builtin.script: ./script.sh
      register: input_result

    - name: 2. Display the raw script output
      ansible.builtin.debug:
        var: input_result.stdout_lines

    - name: 3. Display the raw script output
      ansible.builtin.debug:
        var: input_result.stdout

    - name: 4. Remove ANSI color codes
      ansible.builtin.set_fact:
        Xinput_result_msg: >-
          {{
            input_result.stdout_lines
            | map('regex_replace', '\x1B\[[0-9;]*[A-Za-z]', '')
            | list
          }}
    
    - name: 5. Display cleaned output
      ansible.builtin.debug:
        var: Xinput_result_msg

