#!/bin/bash

# Define the list of files
#files=("file1.txt" "file2.txt" "file3.txt")


files=(
"1A.testing7_mspctl_debug_run_script.yml"
"1B.testing7_mspctl_debug_run_command_site.yml"
)

backupfiles=(
"1A.testing7_mspctl_debug_run_script.yml"
"1B.testing7_mspctl_debug_run_command_site.yml"
)

string1=HS_hostssh01_inner_host_check.yml
string2=HS_hostssh02_inner_host_check.yml
string3=HS_hostssh02_nvidia_smi_inner_host_check.yml
string4=HS_hostssh02_ovn_appctl_inner_host_check.yml
string5=D4_run_hostssh_command.yml
string6=HS_hostssh02_nvidia_vgpu_mgr_inner_host_check.yml

#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) + 0 ))

# Loop through each file
for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"
        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile

        if [[ "$file" != "$string1" && "$file" != "$string2" && "$file" != "$string3" ]]; then
           if [[ "$file" != "$string4" && "$file" != "$string5" && "$file" != "$string6" ]]; then
              echo "" >> $outfile
              echo "" >> $outfile
              echo aph "$file" >> $outfile
              echo "" >> $outfile
              aph "$file" >> $outfile
              echo Processing "$file" finished
              echo
#              sleep 1
           fi
        fi
    else
        echo "Error: $file not found."
    fi
done


