host_roles:
  - r_ncc_health_checks_run_all_gg
  - r_mspctl_debug_run_test_exclude_subset
  - r_allssh_df_kh_grep_elastic_sdb3_gg
  - r_allssh_ll_calm_backup_gg
  - r_allssh_ls_larth_iam_backup_gg
  - r_allssh_curl_get_catalog_k_P1ASEC018  
  - r_allssh_curl_get_catalog_k_P1SMG025   
  - r_ssh_calm_policy_gg

vpc: "IKC2 Calm PC (OTC)"
