#!/bin/bash

# Define the list of files
files=(
"01_testing8_others_cs_grep_v_up_command_gg.yml"
"02_testing8_others_cs_grep_v_up_command_gg.yml"
"03_testing8_others_cs_grep_v_down_command_gg.yml"
"04_testing7_others_cs_grep_v_down_command_gg.yml"
"11_testing8_others_ssh_calm_policy_gg.yml"
"12_testing8_others_ssh_calm_policy_gg.yml"
"13_testing8_others_ssh_calm_policy_50_gg.yml"
"19_testing8_others_all_hostips_svmips_commands.yml"
"20_testing8_others_all_hostips_svmips_commands.yml"
"subr.19_testing8_others_all_hostips_svmips_commands.yml"
"subr.20_testing8_others_allcvms_all_hostips_svmips_commands.yml"
)


#post=$(( ( $(date +%H) * 60 + $(date +%M) ) * 60 + $(date +%S) ))
post=$((  $(date +%H) * 60 + $(date +%M) * 1 + 0 ))

#output=output.$post
#echo $output
# Loop through each file

for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        
        outfile=output."$file"."$post"

        echo Processing "$file" started
        echo "" > $outfile
        echo "---------------------------------" >> $outfile
        echo "$file" >> $outfile
        echo "---------------------------------" >> $outfile
        echo "" >> $outfile

        echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++" >> $outfile
        cat "$file" >> $outfile
        echo "------------------------------------------------------------------" >> $outfile

        if [[ ${file:0:4} != 'subr' ]]; then
           echo "" >> $outfile
           echo "" >> $outfile
           echo aph "$file" >> $outfile
           echo "" >> $outfile
           aph "$file" >> $outfile
           echo Processing "$file" finished
           echo
#           sleep 1
        fi
    else
        echo "Error: $file not found."
    fi
done


