---
- name: Append result to CSV (local)
  delegate_to: localhost
  lineinfile:
    path: "./output_{{ lookup('pipe','date +%Y%m%d') }}.csv"
    create: yes
    line: "{{ inventory_hostname }}, {{ answer }}, {{ remark }}"
