---
- name: how to run mspctl
  hosts: server_15
  gather_facts: false

  tasks:
    - name: 1. Run mspctl debug with command module
      ansible.builtin.command:
        argv:
          - /bin/bash
          - -c
          - |
            source /etc/profile
            mspctl debug run --test_exclude_subset=hosting_pe --log_stdout
#            mspctl_debug_run 
      register: input_result
      changed_when: false
      failed_when: false

    - name: 2. Display the command module raw diagnostic logs
      ansible.builtin.debug:
        var: input_result.stdout_lines

    - name: 3. Display the command module raw diagnostic logs
      ansible.builtin.debug:
        var: input_result.stdout


